version: '3'
services:
  app: &base
    image: keboola-ex-db-informix
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
    environment:
      DB_USER: informix
      DB_PASSWORD: in4mix
      DB_HOST: db
      DB_PROTOCOL: onsoctcp
      DB_LOCALE_VALUE: en_us.8859-1 # cannot be "DB_LOCALE" -> it interferes with ODBC
      DB_PORT: 9088
      DB_DATABASE: test # see create.sql
      DB_SERVER_NAME: informix
    volumes:
      - ssh-keys:/root/.ssh:ro
    depends_on:
      - db
      - sshproxy

  dev:
    <<: *base
    volumes:
      - ssh-keys:/root/.ssh:ro
      - .:/code

  wait:
    image: waisbrot/wait
    depends_on:
      - db
    environment:
      - TARGETS=db:9088
      - TIMEOUT=60

  sshproxy:
    image: keboola/db-component-ssh-proxy:latest
    volumes:
      - ssh-keys:/root/.ssh
    links:
      - db

  db:
    image: ibmcom/informix-developer-database
    environment:
      STORAGE: local
      LICENSE: accept
      INIT_FILE: init.sql
    volumes:
      - ./docker/informix/init.sql:/opt/ibm/config/init.sql

volumes:
  ssh-keys:
