version: '3'
services:
  app: &base
    image: keboola-ex-db-informix
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
    environment:
      DB_USER: informix
      DB_PASSWORD: in4mix
      DB_HOST: db
      DB_PORT: 9088
      DB_DATABASE: sysadmin
      DB_SERVER_NAME: informix
    depends_on:
      - db

  dev:
    <<: *base
    volumes:
      - .:/code

  wait:
    image: waisbrot/wait
    depends_on:
      - db
    environment:
      - TARGETS=db:9088
      - TIMEOUT=60

  db:
    image: ibmcom/informix-developer-database
    environment:
      STORAGE: local
      LICENSE: accept
